Models/ChildModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ChildBinding.Models
{
    public class ChildModel
    {
        public int ChildId
        {
            get;
            set;
        }

        public string Description
        {
            get;
            set;
        }

        public string SomeOtherProperty
        {
            get;
            set;
        }
    }
}

Controllers/BindingDemoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ChildBinding.Models;

namespace ChildBinding.Controllers
{
    public class BindingDemoController : Controller
    {
        // GET: BindingDemo
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult CreateParent()
        {
            ParentModel parentModel = new ParentModel();

            return this.View(parentModel);
        }

        [HttpPost]
        public ActionResult CreateParent(ParentModel parentMode)
        {
            return this.RedirectToAction("Index");
        }
    }
}

Views/BindingDemo/ChildModel.cshtml
@model ChildBinding.Models.ChildModel
@using ChildBinding.Helpers

<tr>
    @using (Html.BeginCollectionItem("ChildModels"))
    {
        <td>
            @if (Model.ChildId == 0)
            {
                <input type="text" name="ChildModels[${index}].ChildId" id="ChildModels__index__ChildId" value="${ChildId}" />
            }
            else
            {
                @Html.EditorFor(m => m.ChildId)
            }
        </td>
        <td>
            @if (Model.ChildId == 0)
            {
                <input type="text" name="ChildModels[${index}].Description" id="ChildModels__index__Description" value="${Description}" />
            }
            else
            {
                @Html.EditorFor(m => m.Description)
            }
        </td>
        <td>
            @if (Model.ChildId == 0)
            {
                <input type="text" name="ChildModels[${index}].SomeOtherProperty" id="ChildModels__index__SomeOtherProperty" value="${SomeOtherProperty}" />
            }
            else
            {
                @Html.EditorFor(m => m.SomeOtherProperty)
            }
        </td>
    }
</tr>

Views/BindingDemo/CreateParent.cshtml
@model ChildBinding.Models.ParentModel
@using ChildBinding.Helpers

@{
    ViewBag.Title = "CreateParent";
}

<h2>CreateParent</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>ParentModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>

            <input type="button" value="Add Child" onclick="addNewChild();" />

            <table id="childModelsGrid">
                <colgroup>
                    <col />
                    <col />
                    <col />
                </colgroup>
                <thead>
                    <tr>
                        <th>Child Id</th>
                        <th>Description</th>
                        <th>Some Other Property</th>
                    </tr>
                </thead>
                <tbody>
                    @Html.EditorFor(model => model.ChildModels)
                </tbody>
            </table>
        </div>

        <script type="text/x-jquery-tmpl" id="childItemTemplate">
            @Html.CollectionItemJQueryTemplate("ChildModel", new ChildBinding.Models.ChildModel());
        </script>

        <script type="text/javascript">
            var viewModel = {
                addNew: function () {
                    var childId = -1;
                    var childDescription = 'FNAR';

                    if (childId === -1) {
                        var templateValue = $("#childItemTemplate").tmpl({ index: viewModel._generateGuid(), ChildId: childId, Description: childDescription });
                        $("#childModelsGrid").find("tbody").append(templateValue);
                    }
                },

                _generateGuid: function () {
                    // Source: http://stackoverflow.com/questions/105034/how-to-create-a-guid-uuid-in-javascript/105074#105074
                    return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function (c) {
                        var r = Math.random() * 16 | 0, v = c == 'x' ? r : (r & 0x3 | 0x8);
                        return v.toString(16);
                    });
                }
            };

            function addNewChild() {
                viewModel.addNew();
            }
        </script>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    <script src="~/Scripts/jQuery.tmpl.js"></script>
}

Views/BindingDemo/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<input type="button" value="Add New Parent Item" onclick="location.href='@Url.Action("CreateParent", "BindingDemo" )'"/>